# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 7 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  lowlighter-github-metrics:
    name: Lowlighter GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Left Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuration
          filename: images/metrics-left.svg
          user: Arch-Frost
          template: classic
          base: header, activity, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Asia/Karachi

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Lines of code
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: repositories

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Notable
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # Contribution Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year


      - name: Right Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuration
          filename: images/metrics-right.svg
          user: Arch-Frost
          template: classic
          base: ""
          config_octicon: yes
          config_timezone: Asia/Karachi

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4

          # People
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Random Code Snippet
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

          # XKCD of the day
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
          